language: python
python:
    - "3.6"
    - "3.7"
sudo: required
dist: xenial
install:
    - pip install -r requirements-dev.txt
    - pip install coverage
    - pip install codecov
script:
    - coverage run_doctests.py
    - nosetests --with-coverage --cover-package=fhirbug.server --cover-package=fhirbug.models --cover-package=fhirbug.db --cover-package=fhirbug.config

after_success:
    - codecov
